version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: '09:00'
      timezone: Asia/Singapore
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
